spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/basictest
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true